### ISSUE TITLE
Successful checks don't return much information

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm-health#63]
We may want checks to return information that is more valuable to users?

Some context from PR #62:

![image](https://user-images.githubusercontent.com/42152676/129604743-05722f96-07a0-4fb4-8b23-ba649f9719ce.png)
and
![image](https://user-images.githubusercontent.com/42152676/129604622-14ed89df-9a86-4473-abeb-c67141050832.png)

ref: https://github.com/openservicemesh/osm-health/pull/62#discussion_r688737924 and https://github.com/openservicemesh/osm-health/pull/62#discussion_r689710307

**Comment by johnsonshi** [comment]
An example is issue #62.

As of now, the osm-health codebase only supports returning successful and failed checks.

For #62, there really isn't any correct notion of "success" or "failure" for that specific check. The presence (or lack thereof) of a traffic split for a destination pod is not a clear-cut answer whether connectivity from pod-to-pod should for fail. The check in #62 isn't really a "pass-fail" check. It is more like a check that should show diagnostic info whether the destination pod has an associated traffic split - it should only show that information without judging success or failure.

osm-health should support indeed support returning additional information for successful and failed checks. An alternative is to return additional check outcome types to reflect "diagnostic-only" checks that aren't pass-fail, such as the one in #62.

**Comment by SanyaKochhar** [comment]
A couple options I'm thinking about --
1. Add more outcomes to checks other than pass/fail. 
 - Pro: keeps checks grouped more logically, eg: SMI checks could remain under the pod to pod connectivity command
2. Move out diagnostic checks into separate commands entirely
- Pro: As a customer, I could imagine wanting to run a preliminary command to check that nothing is actually broken, and then run separate checks for things that I expect to be happening in my mesh the way I have it set up
