### ISSUE TITLE
RDS virtual host domain check for pod-to-pod connectivity looks for pod name instead of service name

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm-health#76]
`HasOutboundDynamicRouteConfigDomainPodCheck` and `HasInboundDynamicRouteConfigDomainPodCheck` currently look for pod names in the domains for the virtual hosts of the `rds-outbound` and `rds-inbound` route configs where they should be looking for the names of the service(s) backed by the pod.

**Comment by johnsonshi** [comment]
Closed with https://github.com/openservicemesh/osm-health/pull/71
